
apiVersion: apps/v1
kind: Deployment
metadata:
  name: riskmatrix-deployment
  labels:
    app: riskmatrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riskmatrix
  template:
    metadata:
      labels:
        app: riskmatrix
    spec:
      containers:
        - name: riskmatrix
          image: riskmatrix:1.0.0
          ports:
            - containerPort: 8080
