apiVersion: v1
kind: Service
metadata:
  name: riskmatrix-service
spec:
  ports:
    - name: riskmatrix-service
      port: 8080
      targetPort: 8080
  selector:
    app: riskmatrix-deployment
status:
  loadBalancer: {}
